// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kino.proto

package ba.tim2.RezervacijaKarata.grpc;

public interface APIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 responseCode = 2;</code>
   */
  int getResponseCode();
}
