// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kino.proto

package ba.tim2.RezervacijaKarata.grpc;

public interface LogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string timestamp = 1;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 1;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>string resource = 2;</code>
   */
  java.lang.String getResource();
  /**
   * <code>string resource = 2;</code>
   */
  com.google.protobuf.ByteString
      getResourceBytes();

  /**
   * <code>string action = 3;</code>
   */
  java.lang.String getAction();
  /**
   * <code>string action = 3;</code>
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>string status = 4;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 4;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
